<a href="https://colab.research.google.com/github/venkat2ram/Kaggle/blob/master/Digit_Recognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd


In [0]:
data=np.array(pd.read_csv(r'/train.csv'))

In [0]:
data.shape

(42000, 785)

In [0]:
data

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [7, 0, 0, ..., 0, 0, 0],
       [6, 0, 0, ..., 0, 0, 0],
       [9, 0, 0, ..., 0, 0, 0]])

In [0]:
train_data=data[0:40000,:]

In [0]:
validation_data=data[40000:42000,:]

In [0]:
X_train=train_data[:,1:785]
X_validation=validation_data[:,1:785]

In [0]:
y_train=train_data[:,0]
y_validation=validation_data[:,0]

In [0]:
y_train=np.zeros((train_data.shape[0],10))
y_validation=np.zeros((validation_data.shape[0],10))
a=0
for i in train_data[:,0]:
  y_train[a,i]=1
  a=a+1
b=0
for i in validation_data[:,0]:
  y_validation[b,i]=1
  b=b+1


In [0]:
from sklearn.neural_network import MLPClassifier

In [0]:
classifier=MLPClassifier()
#50-->76

In [0]:
classifier.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [0]:
y_hat=classifier.predict(X_validation)

In [0]:
sum(y_hat!=y_validation)

77

**-----------------------------------------------------------Test data---------------------------------------------------**

In [0]:
X_test=np.array(pd.read_csv(r'/test.csv'))

In [0]:
y_test=classifier.predict(X_test)

In [0]:
pd.DataFrame(y_test.reshape(-1,1),index=np.array(range(1,28001)),columns=['Label']).to_csv('/submission_5.csv')

**-------------------------------------------Use diferent classifiers---------------------------**

In [0]:
import xgboost as xg
xgb=xg.XGBRFClassifier()
xgb.fit(X_train,y_train)


XGBRFClassifier(base_score=0.5, colsample_bylevel=1, colsample_bynode=0.8,
                colsample_bytree=1, gamma=0, learning_rate=1, max_delta_step=0,
                max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
                n_jobs=1, nthread=None, objective='multi:softprob',
                random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
                seed=None, silent=None, subsample=0.8, verbosity=1)

In [0]:
y_xgb=xgb.predict(X_validation)

In [0]:
sum(y_xgb!=y_validation)

463

In [0]:
import sklearn.neural_network.

**------------------------------------------------Rough-----------------------------------------**

In [0]:
np.array(range(1,28000)).reshape(1,-1)

array([[    1,     2,     3, ..., 27997, 27998, 27999]])

In [0]:
y_test

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0]])

In [0]:
np.where(y_test==1)[1].reshape(-1,1).shape

(28054, 1)

In [0]:
a**2

array([1, 0, 0, 1])

In [0]:
train_data.shape

(40000, 785)

In [0]:
X_validation.shape

(2000, 784)

In [0]:
X_test.shape

(28000, 784)